add config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,7 +11,7 @@ jobs:
       - run:
           name: Get previous results
           command: |
-            export ARTIFACT_LINK="https://circleci.com/api/v1.1/project/github/star-algol/QA8wdio/latest/artifacts"
+            export ARTIFACT_LINK="https://circleci.com/api/v1.1/project/github/bormando/wdiotests/latest/artifacts"
             curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eoq '(http|https)://[a-zA-Z0-9./?=_%:-]*' && wget $(curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*') -O allure-previous.zip
             test -f allure-previous.zip && unzip allure-previous.zip -d allure-previous || echo "Archive not found"
             ls -la
@@ -20,22 +20,26 @@ jobs:
           command: |
             npm run test:chrome:headless
             ls -la
-            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results | echo "Previous report directory not found"
+            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results || echo "Previous report directory not found"
             npm run report:generate
             zip -r allure-report.zip allure-report
       - run:
           when: on_fail
           name: Generate fail results
           command: |
-            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results | echo "Previous report directory not found"
+            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results || echo "Previous report directory not found"
             npm run report:generate
-            zip -r allure-results.zip allure-report
+            zip -r allure-report.zip allure-report
       - store_artifacts:
           path: allure-report.zip
 workflows:
   commit:
     jobs:
-      - build-and-test
+      - build-and-test:
+          filters:
+            branches:
+              only:
+                - master
   nightly:
     triggers:
       - schedule:
